[tool.black]
line-length = 100
target-version = ["py311", "py310", "py39"]
include = "\\.pyi?$"
exclude = "(^/\.venv/|^/venv/|^/build/|^/dist/)"

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["era_v4"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]
exclude = [
    ".venv",
    "venv",
    "build",
    "dist",
    "data",
    "models",
    "outputs",
]

[tool.mypy]
python_version = "3.11"
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true


